# Generated by Django 5.2.5 on 2025-08-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='no value', max_length=100),
            preserve_default=False,
        ),
    ]
