# Generated by Django 5.2.5 on 2025-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
